# Generated by Django 4.2.7 on 2025-06-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Родитель'), ('specialist', 'Специалист'), ('person_with_autism', 'Человек с РАС'), ('caregiver', 'Опекун')], default='parent', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
